# Custom Language File for Launcher Customizer

[ejs.app]
title = "Minecraft For Unowhy"

[ejs.landing]
mediaGitHubURL = "https://github.com/ci2bx/MinecraftForUnowhy"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/ci2bx/MinecraftForUnowhy"
supportLink = "https://github.com/ci2bx/MinecraftForUnowhy/issues"

[ejs.welcome]
welcomeHeader = "MINECRAFT POUR UNOWHY"
welcomeDescription = "Grâce a Minecraft pour UNOWHY, vous pouvez jouez a Minecraft: Java Edition sur votre ordinateur Y13"
welcomeDescCTA = "Vous êtes a quelques cliques de Minecraft."
