[ejs.landing]
updateAvailableTooltip = "Mise a jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Reglages"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUS DE MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;essentiel"
newsButton = "JOURNAL"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez parienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Mise a jour du journal..."
newsErrorFailedSpan = "Erreur lors du chargement du journal"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualitée"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Invalid Value"
loginEmailPlaceholder = "EMAIL OR USERNAME"
loginPasswordError = "* REQUIS"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de passe oublié"
loginRememberMeText = "Se souvenir de moi?"
loginButtonText = "CONNECTION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est directement envoyé a Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié avec Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Choisir"
serverSelectCancel = "Annuler"
accountSelectHeader = "Choisir un compte"
accountSelectConfirm = "Choisir"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Réglages"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "A propos"
navUpdates = "Mises a jour"
navDone = "Terminé"
tabAccountHeaderText = "Réglages du compte"
tabAccountHeaderDesc = "Ajouter des comptes ou géres des comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Réglages de Minecraft"
minecraftTabHeaderDesc = "Option liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran"
autoConnectTitle = "blablabla."
launchDetachedTitle = "Lancer le jeu détaché du launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Réglages des mods"
tabModsHeaderDesc = "Activer ou désactiver des mods."
switchServerButton = "Changer."
requiredMods = "Mods requis"
optionalMods = "Mods optionels"
dropinMods = "Drop-in Mods"
addMods = "Add Mods"
dropinRefreshNote = "(F5 to Refresh)"
shaderpacks = "Pack de shader"
shaderpackDesc = "Activer ou desactiver les shaders. Veuillez notez que les shaders nécessitent un ordinateur performant."
selectShaderpack = "Selectionez le pack de shader"
tabJavaHeaderText = "Réglages Java"
tabJavaHeaderDesc = "Modifier la configuration de java. (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM Maximum"
minRAM = "RAM Minimum"
memoryDesc = "Le minimum de RAM recommendé est 3go. Mettre ces deux paramètres a la même valeur peut réduire le lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "disponible"
javaExecutableTitle = "Executable Java"
javaExecSelDialogTitle = "Choisir l'executable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'éxecutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options du JVM aditielles"
jvmOptsDesc = "Options données au JVM pendant l'éxecution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Réglages du Launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises a jour pre-realease du launcher. (non recommendé)"
allowPrereleaseDesc = "Les pre-Releases incluent des nouvelles fonctionnalités qui n'ont pas été testés entièrement."
dataDirectoryTitle = "Dossier des données"
selectDataDirectory = "Choisir le dossier des données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tout les fichiers du jeu anisi que l'installation locale de Java seront stockés dans le dossier des données.<br>Les captures d'écrans seront stocké dans le dossier spéde la configuration correpondante."
aboutTabHeaderText = "A propos"
aboutTabHeaderDesc = "Voir les informations et les notes de version pour cette version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Release Notes"
changelog = "Changelog"
noReleaseNotes = "Pas de release notes"
viewReleaseNotes = "Voir les Release Notes sur GitHub"
launcherUpdatesHeaderText = "Mise a jour du Launcher"
launcherUpdatesHeaderDesc = "Télécharger et installer les mises a jour du launcher."
checkForUpdates = "Verifier les mises a jour"
whatsNew = "Nouvautés"
updateReleaseNotes = "Mettre a jour les notes de version."

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"


[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue pendent la connexion"
desc = "Une erreur inconnue est survenue. Veuillez verifiez la console pour plus d'informations."

[js.landing.launch]
pleaseWait = "Veuillez patientez.."
failureTitle = "Erreur de lancement"
failureText = "Veuillez verifiez la console pour plus d'informations."
okay = "Ok"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Verification de votre système.."
noCompatibleJava = "Aucune version<br>compatible de Java"
installJavaMessage = "Pour jouer à Minecraft, vous avez besoin d'une installation 64-bit de Java {major}. Voulez-vous l'installez ?"
installJava = "Installer Java"
installJavaManually = "Installer Manuellement"
javaDownloadPrepare = "Perparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur pendant le téléchargement de Java"
javaDownloadFailureText = "Veuillez verifiez la console pour plus d'informations."
javaRequired = "Java est requis<br>pour lancer le jeu"
javaRequiredMessage = 'Pour jouer à Minecraft, vous avez besoin d une installation 64-bit de Java<br><br>Lisez notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide sur Java</a> pour l installez manuellement.'
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour en arrière, j'ai peur."

[js.landing.downloadJava]
findJdkFailure = "Erreur lors de la localisation de la distribution d'OpenJDK."
javaDownloadCorruptedError = "Le JDK a une mauvaise signature, le fichier peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé!"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations de jeu..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Erreur lors du chargement de l'index des ressources. Veuillez verifiez la console pour plus d'informations."
pleaseWait = "Veuillez patientez..."
errorDuringLaunchTitle = "Erreur au lancement"
seeConsoleForDetails = "Veuillez verifiez la console pour plus d'informations."
validatingFileIntegrity = "Validation de l'intégritée des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement.."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'est pas téléchargé proprement. Le jeu ne peut donc pas se lancer.<br><br>Pour résoudre ce problème, désactivez temporairement votre logiciel antivirus et relancez le jeu.<br><br>Veuillez verifiez la console pour plus d'informations."
doneEnjoyServer = "Bon jeu !"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Chargement du journal"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "Touts les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur est survenue"
errorMessage = "L'authentication à Microsoft à échouée. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur est survenue"
errorMessage = "La déconnexion à votre compte Microsoft à échouée. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selectionez un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier avertissement."
lastAccountWarningMessage = "Pour utiliser le launcher vous devez être connecté à au moins un compte. Vous devrez vous connectez après.<br><br>Êtes-vous sur de vouloir vous déconnecter ?"
confirmButton = "Je suis sur."
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Selectionez un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Imposible de suprimer<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Soyez sur que le fichier n'est pas en cours d'utilisation"
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné: Java {version} ({vendor})"
invalidSelection = "Séléction invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponible pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Release Stable"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "Mise a jour du launcher disponible"
newPreReleaseTitle = "Mise a jour Pre-release du launcher disponible"
downloadingButton = "Téléchargement..."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "Vous êtes sur la dernière version du Launcher"
checkForUpdatesButton = "Verifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour..."

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale lors du téléchargement de l'index des ressources"
fatalErrorMessage = "La connexion à nos serveurs n'a pas pu être établiee pour télécharger les ressources. Aucune copie locale n'a été trouvée. <br><br>L'index des ressources est un fichier essentiel qui vous donnes les dernière informations de Minecraft. Le launcher ne peut pas démmarer sans. Verifier votre connexion a Internet et relancer le launcher."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Imposible d'actualiser la connexion."
failedMessage = "Nous sommes imposible d'actualiser la connexion pour <strong>{account}</strong>. Choisissez un autre compte ou connectez-vous a nouveau."
failedMessageSelectAnotherAccount = "Nous sommes imposible d'actualiser la connexion pour <strong>{account}</strong>. Connectez-vous a nouveau."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Verifier les mises à jour"
